export type MerchProduct = {
  id: string;
  name: string;
  description: string;
  priceCents: number;
  image: string;
  badge: string;
  category: 'clothing' | 'headwear' | 'creator-kit' | 'business-cards' | 'desk-gear' | 'promo-tools';
  shortLabel: string;
  bestFor: string;
  leadTime: string;
  featureList: string[];
};

export const MERCH_PRODUCTS: MerchProduct[] = [
  {
    id: 'closer-uniform-hoodie',
    name: 'Closer Uniform Hoodie',
    description: 'Heavyweight black hoodie built for daily-wear identity. The FSA ELITE chest mark signals you’re serious before you say a word.',
    priceCents: 7900,
    image: '/logo.png',
    badge: 'Top Seller',
    category: 'clothing',
    shortLabel: 'Signature Layer',
    bestFor: 'Reps who want their identity to land before they even say hello.',
    leadTime: 'Ships after payment confirmation.',
    featureList: ['Premium heavyweight fabric', 'FSA ELITE chest branding', 'Showroom and street-ready fit'],
  },
  {
    id: 'elite-cap-series',
    name: 'FSA ELITE Cap Series',
    description: 'Structured cap that locks in your look on the floor, on camera, and everywhere in between.',
    priceCents: 4200,
    image: '/logo.png',
    badge: 'Daily Wear',
    category: 'headwear',
    shortLabel: 'Identity Piece',
    bestFor: 'Closers building a consistent look whether they’re on the floor or on camera.',
    leadTime: 'Ships after payment confirmation.',
    featureList: ['Structured front panel', 'Clean creator-ready silhouette', 'Pairs with any closer fit'],
  },
  {
    id: 'self-promo-brand-kit',
    name: 'Self-Promo Brand Kit',
    description: 'The full stack: gear and brand assets designed to make you look established, not like you’re still building.',
    priceCents: 11900,
    image: '/og-image.jpg',
    badge: 'Bundle',
    category: 'creator-kit',
    shortLabel: 'Closer Stack',
    bestFor: 'Members who want their name to carry weight before the conversation starts.',
    leadTime: 'Digital and merch bundle timing varies by item.',
    featureList: ['Gear + digital brand assets included', 'Positions you as an established name', 'Built for reps who want to stand out fast'],
  },
  {
    id: 'premium-business-cards',
    name: 'Premium Business Cards (250 ct)',
    description: 'Thick matte stock. Your name, logo, and QR code — printed to hand out at every appointment, event, and follow-up.',
    priceCents: 4900,
    image: '/logo-badge.jpg',
    badge: 'Essential',
    category: 'business-cards',
    shortLabel: 'Closer Essential',
    bestFor: 'Every rep who shakes a hand and wants to be remembered.',
    leadTime: 'Production timing applies before fulfillment.',
    featureList: ['250 premium matte cards', 'QR code + logo included', 'Sharper than a handshake alone'],
  },
  {
    id: 'digital-business-card',
    name: 'Digital Business Card',
    description: 'Tap your card, share your entire contact profile instantly. No app needed on their end — just a faster, sharper first impression.',
    priceCents: 2900,
    image: '/logo-badge.jpg',
    badge: 'New',
    category: 'business-cards',
    shortLabel: 'Fastest Intro',
    bestFor: 'Reps who want to give their info once and have it stick.',
    leadTime: 'Digital setup timing varies by customization needs.',
    featureList: ['Tap-to-share NFC technology', 'Links to your full contact profile', 'No app required on their end'],
  },
  // ─── Desk Gear ─────────────────────────────────────────────────────────
  {
    id: 'branded-leather-portfolio',
    name: 'Branded Leather Portfolio',
    description: 'Professional A4 portfolio with your name or logo — walk into every meeting looking like you own the room.',
    priceCents: 3900,
    image: '/logo.png',
    badge: 'Pro Tool',
    category: 'desk-gear',
    shortLabel: 'Meeting Ready',
    bestFor: 'Reps who want to command respect before they say a word.',
    leadTime: 'Ships after payment confirmation.',
    featureList: ['Embossed logo option', 'Card slots + notepad holder', 'Premium PU leather finish'],
  },
  {
    id: 'custom-notepad-pack',
    name: 'Custom Branded Notepad Pack',
    description: 'Your logo on every page — 50-sheet custom notepads that double as a self-promo tool every time you hand one over.',
    priceCents: 2400,
    image: '/logo.png',
    badge: 'Daily Use',
    category: 'desk-gear',
    shortLabel: 'Rep Signature',
    bestFor: 'Salespeople who want their brand visible at every desk interaction.',
    leadTime: 'Production and shipping timeline applies.',
    featureList: ['50 sheets per pad', 'Custom logo printed header', 'Tear-off format for easy handout'],
  },
  {
    id: 'desktop-nameplate',
    name: 'Desk Nameplate & Stand',
    description: 'Your name, your title, your presence — on the desk for every walk-in to see.',
    priceCents: 1900,
    image: '/logo.png',
    badge: 'Identity',
    category: 'desk-gear',
    shortLabel: 'First Impression',
    bestFor: 'Any rep with a desk, showroom, or office who wants instant credibility.',
    leadTime: 'Production and shipping timeline applies.',
    featureList: ['Custom name + title engraving', 'Premium metal frame', 'Desktop and wall-mount options'],
  },
  {
    id: 'executive-pen-set',
    name: 'Executive Pen Set',
    description: "Sign deals with a pen that says you've already made up your mind. Engrave your name and hand one to every prospect.",
    priceCents: 2200,
    image: '/logo.png',
    badge: 'Classic',
    category: 'desk-gear',
    shortLabel: 'Deal Closer',
    bestFor: 'Closers who know every detail is part of the pitch.',
    leadTime: 'Ships after payment confirmation.',
    featureList: ['Set of 5 premium pens', 'Custom name engraving available', 'Box-ready for gifting or leave-behind'],
  },
  // ─── Promo Tools ───────────────────────────────────────────────────────
  {
    id: 'presentation-folder',
    name: 'Custom Presentation Folder',
    description: 'Leave behind more than your card — a branded folder with your name on the cover that keeps your proposal front and center.',
    priceCents: 3200,
    image: '/logo.png',
    badge: 'Closer Tool',
    category: 'promo-tools',
    shortLabel: 'Leave-Behind Pro',
    bestFor: 'Reps presenting proposals, quotes, or follow-up packages to prospects.',
    leadTime: 'Production and shipping timeline applies.',
    featureList: ['Full-color custom print', 'Business card pocket included', 'Professional gloss or matte finish'],
  },
  {
    id: 'branded-usb-drives',
    name: 'Branded USB Drive Pack (10ct)',
    description: 'Load your presentation, price sheet, or video and hand it directly to the decision-maker — your brand stays with them.',
    priceCents: 3500,
    image: '/logo.png',
    badge: 'Tech Identity',
    category: 'promo-tools',
    shortLabel: 'Tech Leave-Behind',
    bestFor: 'B2B and high-ticket reps who want to leave a powerful digital first impression.',
    leadTime: 'Ships after payment confirmation.',
    featureList: ['10 branded USB drives (8GB)', 'Custom logo imprint', 'Pre-load content on request'],
  },
  {
    id: 'phone-tablet-stand',
    name: 'Branded Phone & Tablet Stand',
    description: 'Your logo on your desk, your screen at eye level — for video calls, demos, and every digital presentation.',
    priceCents: 2800,
    image: '/logo.png',
    badge: 'Desk Flex',
    category: 'promo-tools',
    shortLabel: 'Screen Presence',
    bestFor: 'Reps who run video calls, Zoom demos, or digital presentations daily.',
    leadTime: 'Ships after payment confirmation.',
    featureList: ['Adjustable angle + height', 'Logo engraving on base', 'Fits phone and tablet'],
  },
  {
    id: 'sales-professional-tote',
    name: 'Sales Professional Tote',
    description: 'Walk between appointments with a bag that does the talking — custom-branded canvas tote built for the working rep.',
    priceCents: 3400,
    image: '/logo.png',
    badge: 'Carry Identity',
    category: 'promo-tools',
    shortLabel: 'Mobile Brand',
    bestFor: 'Reps who are constantly on the move and want their brand visible everywhere.',
    leadTime: 'Ships after payment confirmation.',
    featureList: ['Heavy-duty canvas construction', 'Custom logo print on both sides', 'Interior laptop pocket'],
  },
  // ─── Headwear Expansion ────────────────────────────────────────────────
  {
    id: 'snapback-closer-cap',
    name: 'Closer Snapback',
    description: 'Flat-brim snapback with your name or brand on the front panel. The look that says you close — before you open your mouth.',
    priceCents: 3800,
    image: '/logo.png',
    badge: 'Street Ready',
    category: 'headwear',
    shortLabel: 'Street Identity',
    bestFor: 'Reps who want a casual-confident look on and off the floor.',
    leadTime: 'Ships after payment confirmation.',
    featureList: ['Flat-brim snapback fit', 'Embroidered name or logo', 'One size fits most'],
  },
  {
    id: 'beanie-winter-series',
    name: 'FSA ELITE Branded Beanie',
    description: 'Stay sharp through cold-weather appointments. Clean knit beanie with your logo embroidered on the fold.',
    priceCents: 2800,
    image: '/logo.png',
    badge: 'Winter Drop',
    category: 'headwear',
    shortLabel: 'Cold-Weather Closer',
    bestFor: 'Reps working outdoor lots, door-to-door, or cold-climate territory.',
    leadTime: 'Ships after payment confirmation.',
    featureList: ['Premium acrylic knit', 'Embroidered logo on cuff', 'Pairs with the Closer Uniform Hoodie'],
  },
  // ─── Pen & Pencil Sets ─────────────────────────────────────────────────
  {
    id: 'custom-pencil-pack',
    name: 'Custom Branded Pencil Pack (12ct)',
    description: 'Your name on a dozen pencils — for the desk, the client table, and every leave-behind that keeps your brand in sight long after you walk out.',
    priceCents: 1600,
    image: '/logo.png',
    badge: 'Leave-Behind',
    category: 'desk-gear',
    shortLabel: 'Daily Touch',
    bestFor: 'Reps who want cheap, high-frequency brand repetition with every client interaction.',
    leadTime: 'Production and shipping timeline applies.',
    featureList: ['12 premium pencils per pack', 'Custom name or logo imprint', 'Sharp, professional finish'],
  },
  {
    id: 'signature-closer-pen',
    name: 'Signature Closer Pen (Single)',
    description: 'One pen. Your name on it. The one you hand across the desk at close. Make the moment memorable.',
    priceCents: 1200,
    image: '/logo.png',
    badge: 'The Close',
    category: 'desk-gear',
    shortLabel: 'Close Tool',
    bestFor: 'Reps who want a premium single pen engraved for presenting at the signing moment.',
    leadTime: 'Ships after payment confirmation.',
    featureList: ['Single premium metal pen', 'Laser-engraved name', 'Velvet gift box included'],
  },
  // ─── Custom Design Service ─────────────────────────────────────────────
  {
    id: 'custom-merch-design-request',
    name: 'Custom Merch Design Request',
    description: 'Got a specific idea — a logo, a color, a product type, an idea for your team? Submit a custom order request and we build it for you.',
    priceCents: 0,
    image: '/logo.png',
    badge: 'Custom Order',
    category: 'creator-kit',
    shortLabel: 'Build It Your Way',
    bestFor: 'Reps and teams who want something specific that is not already in the catalog.',
    leadTime: 'Timeline discussed upon request submission.',
    featureList: ['Custom product type', 'Your logo, colors, and text', 'Minimum quantities vary by item — contact us to start'],
  },
];
